from pyecharts import options as opts
from pyecharts.charts import Tree

def tree_base() -> Tree:
    data = [
        {
            "children":[
                {
                    "children":[
                        {"name":"马克思主义的创立与发展"},
                        {"name":"马克思主义的鲜明特征"},
                        {"name":"马克思主义的当代价值"},
                        {"name":"自觉学习和运用马克思主义"},
                    ],
                    "name":"导论"},
                {
                    "children":[
                        {
                            "children":[
                                {"name":"物质及其存在形态"},
                                {"name":"物质与意识的辩证关系"},
                                {"name":"世界的物质统一性"},
                            ],
                            "name":"世界多样性与物质统一性"},
                        {
                            "children":[
                                {"name":"联系和发展的普遍性"},
                                {"name":"联系和发展的基本环节"},
                                {"name":"对立统一规律是事物发展的根本规律"},
                                {"name":"量变质变规律和否定之否定规律"},
                            ],
                            "name":"事物的联系和发展"},
                        {
                            "children":[
                                {"name":"唯物辩证法是科学的认识方法"},
                                {"name":"辩证思维方法与现代科学思维方法"},
                                {"name":"学习唯物辩证法，不断增强思维能力"},
                            ],
                            "name":"唯物辩证法是认识世界和改造世界的根本方法"},
                    ],
                    "name":"世界的物质性及发展规律"},
                {
                    "children":[
                        {
                            "children":[
                                {"name":"实践的本质与基本结构"},
                                {"name":"认识的本质与过程"},
                                {"name":"实践与认识的辩证运动及其规律"},
                            ],
                            "name":"实践与认识"},
                        {
                            "children":[
                                {"name":"真理的客观性、绝对性和相对性"},
                                {"name":"真理的检验标准"},
                                {"name":"真理与价值的辩证统一"},
                            ],
                            "name":"真理与价值"},
                        {
                            "children":[
                                {"name":"认识世界和改造世界相结合"},
                                {"name":"一切从实际出发，实事求是"},
                                {"name":"实现理论创新和实践创新的良性互动"},
                            ],
                            "name":"认识世界和改造世界"},
                    ],
                    "name":"实践与认识及其发展规律"},
                {
                    "children":[
                        {
                            "children":[
                                {"name":"社会存在与社会意识"},
                                {"name":"生产力与生产关系的矛盾运动及其规律"},
                                {"name":"经济基础与上层建筑的矛盾运动及其规律"},
                                {"name":"社会形态更替的一般规律及特殊形式"},
                            ],
                            "name":"社会基本矛盾及其运动规律"},
                        {
                            "children":[
                                {"name":"社会基本矛盾在历史发展中的作用"},
                                {"name":"阶级斗争和社会革命在阶级社会发展中的作用"},
                                {"name":"改革在社会发展中的作用"},
                                {"name":"科学技术在社会发展中的作用"},
                            ],
                            "name":"社会历史发展的动力"},
                        {
                            "children":[
                                {"name":"民群众是历史的创造者"},
                                {"name":"个人在社会历史中的作用"},
                            ],
                            "name":"人民群众在历史发展中的作用"},
                    ],
                    "name":"人类社会及其发展规律"},
                {
                    "children":[
                        {
                            "children":[
                                {"name":"商品经济的形成和发展"},
                                {"name":"价值规律及其作用"},
                                {"name":"以私有制为基础的商品经济的基本矛盾"},
                                {"name":"科学认识马克思劳动价值论"},
                            ],
                            "name":"商品经济和价值规律"},
                        {
                            "children":[
                                {"name":"资本主义经济制度的产生"},
                                {"name":"劳动力成为商品与货币转化为资本"},
                                {"name":"资本主义所有制"},
                                {"name":"生产剩余价值是资本主义生产方式的绝对规律"},
                                {"name":"资本主义的基本矛盾与经济危机"},
                            ],
                            "name":"资本主义经济制度的本质"},
                        {
                            "children":[
                                {"name":"资本主义政治制度及其本质"},
                                {"name":"资本主义意识形态及其本质"},
                            ],
                            "name":"资本主义政治制度和意识形态"},
                    ],
                    "name":"资本主义的本质及规律"},
                {
                    "children":[
                        {
                            "children":[
                                {"name":"资本主义从自由竞争到垄断"},
                                {"name":"垄断资本主义的发展"},
                                {"name":"经济全球化及其影响"},
                            ],
                            "name":"垄断资本主义的形成与发展"},
                        {
                            "children":[
                                {"name":"第二次世界大战后资本主义变化的新特点"},
                                {"name":"2008年国际金融危机以来资本主义的矛盾与冲突"},
                            ],
                            "name":"正确认识当代资本主义的新变化"},
                        {
                            "children":[
                                {"name":"资本主义的历史地位"},
                                {"name":"资本主义为社会主义所代替的历史必然性"},
                            ],
                            "name":"资本主义的历史地位和发展趋势"},
                    ],
                    "name":"资本主义的发展及其趋势"},
                {
                    "children":[
                        {
                            "children":[
                                {"name":"社会主义从空想到科学"},
                                {"name":"社会主义从理想到现实"},
                                {"name":"社会主义从一国到多国"},
                                {"name":"社会主义在中国焕发出强大生机活力"},
                            ],
                            "name":"社会主义五百年的历史进程"},
                        {
                            "children":[
                                {"name":"科学社会主义一般原则及其主要内容"},
                                {"name":"正确把握科学社会主义一般原则"},
                            ],
                            "name":"科学社会主义一般原则"},
                        {
                            "children":[
                                {"name":"经济文化相对落后国家建设社会主义的长期性"},
                                {"name":"社会主义发展道路的多样性"},
                                {"name":"社会主义在实践探索中开拓前进"},
                            ],
                            "name":"在实践中探索现实社会主义的发展规律"},
                    ],
                    "name":"社会主义的发展及其规律"},
                {
                    "children":[
                        {
                            "children":[
                                {"name":"预见未来社会的方法论原则"},
                                {"name":"共产主义社会的基本特征"},
                            ],
                            "name":"展望未来共产主义新社会"},
                        {
                            "children":[
                                {"name":"实现共产主义是历史发展的必然"},
                                {"name":"实现共产主义是长期的历史过程"},
                            ],
                            "name":"实现共产主义是历史发展的必然趋势"},
                        {
                            "children":[
                                {"name":"坚持远大理想与共同理想的辩证统一"},
                                {"name":"坚定理想信念，投身新时代中国特色社会主义事业"},
                            ],
                            "name":"共产主义远大理想与中国特色社会主义共同理想"},
                    ],
                    "name":"共产主义崇高理想及其最终实现"},
                {"name":"后记"},
            ],
            "name":"马克思主义基本原理概论"}
    ]

    c = (
        Tree(init_opts=opts.InitOpts(width = "1300px",height = "1300px"))
        .add("", data, collapse_interval=4, layout="radial", symbol="emptyCircle", 
             itemstyle_opts=opts.ItemStyleOpts(border_color="rgb(12, 12, 150)"), 
             pos_left="20%", 
             leaves_label_opts=opts.LabelOpts(horizontal_align="center", vertical_align = "top"), 
             label_opts=opts.LabelOpts(horizontal_align="center", vertical_align = "bottom")
             )
        .set_global_opts(title_opts = opts.TitleOpts(title="Radial Tree Layout"))
    )
    return c

c = tree_base()
c.render()